[32m[I 2024-05-29 16:09:54,891][39m A new study created in memory with name: no-name-f0314b2f-33c2-473a-8659-f53704e00a25
Epoch 1 - Training:   0%|                                                                       | 0/257 [00:00<?, ?it/s]/home/disi/ml/.venv/lib/python3.11/site-packages/torch/autograd/graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Epoch 1 - Training:   1%|â–‹                                                              | 3/257 [00:01<01:23,  3.03it/s]







































Epoch 1 - Training: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 257/257 [01:19<00:00,  3.22it/s]
2024-05-29 16:11:15,259 - training_logger - INFO - Training: Average loss: 5.3131, Accuracy: 0.64%
2024-05-29 16:11:15,259 - training_logger - INFO - Epoch 1 completed in 79.77 seconds
Validation:  27%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ                                                    | 15/56 [00:01<00:03, 10.87it/s]

Validation: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 56/56 [00:05<00:00, 10.76it/s]
[33m[W 2024-05-29 16:11:20,473][39m Trial 0 failed with parameters: {'dropout_rate': 0.389070970442277, 'optimizer': 'SGD', 'learning_rate': 9.407008476088531e-05, 'weight_decay': 1.066095276791422e-06, 'momentum': 0.6412645776665816} because of the following error: TypeError('expected str, bytes or os.PathLike object, not NoneType').
Traceback (most recent call last):
  File "/home/disi/ml/.venv/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/disi/ml/intromlproject/training-main-optune.py", line 116, in objective
    save_path = os.path.join(config['checkpoint'], f"OPTUNA_trial{trial}_{config['model_name']}_{config['dataset_name']}_epoch{epoch}.pth")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
[33m[W 2024-05-29 16:11:20,474][39m Trial 0 failed with value None.
Traceback (most recent call last):
  File "/home/disi/ml/intromlproject/training-main-optune.py", line 172, in <module>
    main(config)
  File "/home/disi/ml/intromlproject/training-main-optune.py", line 126, in main
    study.optimize(objective, n_trials=trials, timeout=600)
  File "/home/disi/ml/.venv/lib/python3.11/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/disi/ml/.venv/lib/python3.11/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/home/disi/ml/.venv/lib/python3.11/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/disi/ml/.venv/lib/python3.11/site-packages/optuna/study/_optimize.py", line 247, in _run_trial
    raise func_err
  File "/home/disi/ml/.venv/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/disi/ml/intromlproject/training-main-optune.py", line 116, in objective
    save_path = os.path.join(config['checkpoint'], f"OPTUNA_trial{trial}_{config['model_name']}_{config['dataset_name']}_epoch{epoch}.pth")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
Train loss: 5.313, Train accuracy: 0.644
Validation loss: 11.975, Validation accuracy: 0.614